### ISSUE TITLE
App tests are passing on CI, but failing on local

### ISSUE THREAD

**Issue by IvanJov** [meteortesting/meteor-mocha#29]
Hi,

I am having an issue on Circle CI. When I run a command on the local machine, tests are failing (and they should), but when I run it on Circle CI, they are passing. For some reason, the package is always giving 0 exit code. The package works really good on packages test but fails on apps.

This is the command I am using:
```
TEST_CLIENT=0 meteor test --driver-package dispatch:mocha --once
```

Any idea what can be wrong here?

**Comment by aldeed** [comment]
@IvanJov Is it possible for you to make a small open source app that has this issue and runs on circleCI? Will be easier to figure out what is happening
