### ISSUE TITLE
Add ability to set mocha's --timeout

### ISSUE THREAD

**Issue by workflow** [meteortesting/meteor-mocha#34]
Related: https://github.com/practicalmeteor/meteor-mocha-core/pull/9

I attempted to fix this here: https://github.com/DispatchMe/meteor-mocha/pull/33, but it looks like the option isn't doing anything when arriving at `meteor-mocha-core`s `mochaInstance`. Any hints for me?

Thanks again for this package! Very useful addition to the Meteor testing landscape :bowing_man:

**Comment by hexsprite** [comment]
i wonder if this is now possible with the latest updates ? @SimonSimCity any thoughts on this? I keep running into timeouts in my tests on the CI server ;(

**Comment by SimonSimCity** [comment]
@hexsprite would you have the time to create a PR and prove it working on the client and server? This would help me tons ...

Please start by forking https://github.com/meteortesting/meteor-mocha-core and checking it out into the `packages` folder in your meteor application.

**Comment by hexsprite** [comment]
from what I can see you need to set the timeout within meteor-mocha-core since the global timeout must be set at Mocha instance creation. I'll send a PR to meteor-mocha-core for that. Just tested it and it works well.

**Comment by aldeed** [comment]
@hexsprite I believe you can set client options just prior to running as is currently done here: https://github.com/meteortesting/meteor-mocha/blob/master/package/client.js#L44-L46

Mocha instance has a [timeout method](https://github.com/mochajs/mocha/blob/5fc58458395d8a9bc75daae97042af78dc94cc7a/lib/mocha.js#L446-L449) you can call to change it after instantiation.

**Comment by aldeed** [comment]
Note that there's a PR attempting this, which I think would work fine if just changed to use the timeout method rather than trying to set options.timeout. https://github.com/meteortesting/meteor-mocha/pull/33

**Comment by mitar** [comment]
So I just realized you can also do `this.timeout(5000);` inside `describe` to raise timeout for a particular test suite. I think this is also useful as a workaround.

I tested the #33 by changing it to call `mochaInstance.timeout(timeout)` but it didn't work.

**Comment by hexsprite** [comment]
I haven't had time to look into the client side yet so if anyone feels called then by all means! :) For server tests my PR to `meteor-mocha-core` solves it and my CI tests are happy again.

**Comment by mitar** [comment]
This one #9?

**Comment by hexsprite** [comment]
@mitar https://github.com/hexsprite/meteor-mocha-core/commit/d623f477ded007b41f406db9ae139fa514716cb1

**Comment by SimonSimCity** [comment]
Fixed, see https://github.com/meteortesting/meteor-mocha#specify-global-timeout
