### ISSUE TITLE
Problem with server tests

### ISSUE THREAD

**Issue by PositronicBrain** [meteortesting/meteor-mocha#38]
Everything works well if I do

    TEST_BROWSER_DRIVER='chrome' meteor test --driver-package dispatch:mocha

or:

    TEST_SERVER=0 meteor test --once --driver-package dispatch:mocha

But if the command is: 

    meteor test --driver-package dispatch:mocha

I get:

    I20170702-20:02:56.373(2)?                    
    I20170702-20:02:56.374(2)? --------------------------------
    I20170702-20:02:56.375(2)? ----- RUNNING SERVER TESTS -----
    I20170702-20:02:56.376(2)? --------------------------------
    I20170702-20:02:56.376(2)? 
    I20170702-20:02:56.377(2)? 
    I20170702-20:02:56.378(2)? 
    I20170702-20:02:56.378(2)?   0 passing (0ms)
    I20170702-20:02:56.380(2)? 
    I20170702-20:02:56.381(2)? Load the app in a browser to run client tests, or set the 
    TEST_BROWSER_DRIVER environment variable. See https://github.com/DispatchMe/meteor-
    mocha/blob/master/README.md#run-app-tests
    => Exited with code: 0
    => Your application is crashing. Waiting for file change.
   
Could it be because all my `describe` are wrapped in `if(Meteor.isClient)`? There are no server tests right now.

**Comment by mdorn** [comment]
@PositronicBrain I have the same problem you describe.  I don't think it has anything to do with server tests.  If you set the `TEST_WATCH` flag, it should work as expected:

    TEST_WATCH=1 meteor test --driver-package meteortesting:mocha

**Comment by aldeed** [comment]
Every command needs either TEST_WATCH=1 or --once. If it's still broken when you add TEST_WATCH, then we would need a link to a simple app that reproduces this issue.
