### ISSUE TITLE
Tests keep restarting without changing anything

### ISSUE THREAD

**Issue by theodorDiaconu** [meteortesting/meteor-mocha#44]
Meteor: 1.6.0

TEST_BROWSER_DRIVER=chrome meteor test-packages --driver-package meteortesting:mocha packages/redis-oplog

Server keeps restarting:
```

I20171104-16:13:41.342(2)? --------------------------------
I20171104-16:13:41.342(2)? SERVER FAILURES: 0
I20171104-16:13:41.343(2)? CLIENT FAILURES: 0
I20171104-16:13:41.343(2)? --------------------------------
=> Exited with code: 0
I20171104-16:13:43.145(2)? RedisOplog - Established connection to redis.
I20171104-16:13:43.180(2)? 
I20171104-16:13:43.181(2)? --------------------------------
I20171104-16:13:43.181(2)? ----- RUNNING SERVER TESTS -----
I20171104-16:13:43.181(2)? --------------------------------
```

If I use TEST_WATCH=1 it works fine.

**Comment by aldeed** [comment]
@theodorDiaconu You are missing `--once` flag in the command. Without that, Meteor is in watch mode.

Unfortunately, the test driver doesn't know which mode Meteor is in, so the `TEST_WATCH=1` is for the driver while the `--once` is for Meteor.

Meteor in watch mode: Default
Meteor in "once" mode: --once
Driver in watch mode: TEST_WATCH=1
Driver in "once" mode: Default

The key is to make sure you put both into watch mode or both into "once" mode.
