### ISSUE TITLE
Phantom doesn't show browser report

### ISSUE THREAD

**Issue by lorensr** [meteortesting/meteor-mocha#53]
Page is blank and console shows:

![image](https://user-images.githubusercontent.com/251288/36623982-11d01074-18d8-11e8-848d-7f4c149b69f6.png)

Steps to reproduce:
- `meteor create app` (version 1.6.1)
- `meteor add meteortesting:mocha`
- `meteor npm i --save-dev phantomjs-prebuilt`

```
$ TEST_WATCH TEST_BROWSER_DRIVER=phantomjs meteor test --driver-package meteortesting:mocha 
```

repro: https://github.com/lorensr/meteor-mocha-chrome-repro/tree/bug/phantom

**Comment by SimonSimCity** [comment]
@lorensr If you open the tests in your browser, this browser will run the tests.

When defining `TEST_BROWSER_DRIVER` you tell the system that you want to run the client-tests in a specific browser - `phantomjs` in your case. This browser is then starts headless, runs all the tests and writes the report out on the console, which is caught by the browser-runner on the server and printed.

But in your case, you opened the application in - I guess it's chrome? This means that what you see in the console there is the result of the client-tests run in chrome.

Please show the full output of the command on the console. This should either include a warning of why the tests couldn't run on `phantom` or the test results.

@aldeed I guess we need a more declarative way of describing this step in the manual: https://github.com/meteortesting/meteor-mocha#run-client-tests-in-any-browser-manually

It should state more clearly that you actually are running the tests in the browser you're executing it in. Maybe we should also add a `div` showing a clear warning if `TEST_BROWSER_DRIVER` is defined which should state that you most-likely are running this in the wrong browser 😅

**Comment by aldeed** [comment]
> Maybe we should also add a div if TEST_BROWSER_DRIVER is defined which shows a clear warning stating that you most-likely are currently running the tests in the wrong browser

Makes sense to me

**Comment by SimonSimCity** [comment]
Since we do not ask the browser to click anywhere on the screen, record screenshots or the-like, this shouldn't have any affect to the outcome of any test, right?

Does this means we could actually always show it if `TEST_BROWSER_DRIVER` is set?

**Comment by SimonSimCity** [comment]
Closing this ticket because Phantom is deprecated (https://github.com/meteortesting/meteor-browser-tests#phantomjs)
