### ISSUE TITLE
Showing server/ test results in browser?

### ISSUE THREAD

**Issue by kkor** [meteortesting/meteor-mocha#57]
I have the following tests in my folder structure:

imports/api/collections/a.test.ts
imports/api/collections/server/b.test.ts
imports/ui/client/c.test.ts

I run the tests with `TEST_WATCH=1 meteor test --driver-package meteortesting:mocha`.

The results for both server tests a.test.ts and b.test.ts are shown in the console under "RUNNING SERVER TESTS" . 
But only the results for server test a and the client test c both show up in the tests at http://localhost:3000/. If I move the b.test.ts file into the collections folder it does show up.

Does anyone know why the subfolder tests aren't showing up or how to fix it? I tried MOCHA_GREP, but I seem to have the syntax wrong, because 'imports/**/*.ts' runs 0 tests? 

Thanks!

**Comment by mitar** [comment]
I am not sure that results from server tests are shown ever in the browser? I think this is not yet implemented. See #70. I think you might be running your "server" tests in the browser, and this is why it is showing there, and your real server tests do not run in the browser, this is why you are not seeing them.

**Comment by mitar** [comment]
In [Meteor guide](https://guide.meteor.com/images/mocha-test-results.png) I can see both client and server tests in a browser. How is that possible?

**Comment by SimonSimCity** [comment]
I have to admit, that I was planning to update the meteor guide with what I now write here (planned to do in https://github.com/meteortesting/meteor-mocha/issues/80):

As of the time writing, this is not possible with this plugin, but was archived by https://github.com/practicalmeteor/meteor-mocha, which doesn't work in Meteor 1.6.0 due to an update of the coffeescript library.

https://github.com/cult-of-coders/meteor-mocha is a fork of the mentioned repository which got an upgrade to coffeescript 2 - maybe more. So - choose your weapon.

In my opinion, the package by `cult-of-coders` is a better fit for you if you want to see all results in the browser. This package makes it very easy to run your tests in the console (even a headless like travis or docker).

If there are people, willing to take the time needed to implement an option for this plugin which would allow reporting of all tests to the browser, I'm very open for providing the knowledge needed.

**Comment by SimonSimCity** [comment]
Please take a look at the Meteor Guide at the chapter `Application Structure` (https://guide.meteor.com/structure.html):

Here are some of the important parts:

> Meteor will load all files outside of any directory named `imports/` in the application using the default file load order rules (also called “eager evaluation or loading”). It is recommended that you create exactly two eagerly loaded files, `client/main.js` and `server/main.js`, in order to define explicit entry points for both the client and the server. Meteor ensures that any file in any directory named `server/` will only be available on the server, and likewise for files in any directory named `client/`. This also precludes trying to import a file to be used on the server from any directory named `client/` even if it is nested in an `imports/` directory and vice versa for importing client files from `server/`.

> Any directory named `server/` is not loaded on the client. Similar to wrapping your code in `if (Meteor.isServer) { ... }`, except the client never even receives the code.

> Any directory named `client/` is not loaded on the server. Similar to wrapping your code in `if (Meteor.isClient) { ... }`. All files loaded on the client are automatically concatenated and minified when in production mode.

> All JavaScript files outside special directories are loaded on both the client and the server. Meteor provides the variables Meteor.isClient and Meteor.isServer so that your code can alter its behavior depending on whether it’s running on the client or the server.

Another thing new in Meteor 1.7.0 might change this behavior (https://docs.meteor.com/changelog.html#changes-6):

> Applications may now specify client and server entry point modules in a newly-supported "meteor" section of package.json:
> ```
>"meteor": {
>  "mainModule": {
>    "client": "client/main.js",
>    "server": "server/main.js"
>  }
>}
>```
> When specified, these entry points override Meteor's default module loading semantics, rendering imports directories unnecessary. If mainModule is left unspecified for either client or server, the default rules will apply for that architecture, as before. To disable eager loading of modules on a given architecture, simply provide a mainModule value of false[...]

This said, this "bug" really is a feature 😊

**Comment by thebarty** [comment]
try out `cultofcoders:mocha` it shows both results in the browser
