### ISSUE TITLE
Run only from directory

### ISSUE THREAD

**Issue by stolinski** [meteortesting/meteor-mocha#58]
I'm looking to limit tests finding to only the /imports/api  directory of my app. Is there any way to do that with this package? I'm having a hard time finding a way to make that work. Right now it's discovering all tests in my /imports/ui and since the code isn't in client or server, limiting that way isn't going to work.

**Comment by aldeed** [comment]
Determining which tests to run is handled by Meteor. See https://guide.meteor.com/testing.html#test-modes

It doesn't seem like they have a way to limit, but maybe there's something undocumented. You could ask on forums
