### ISSUE TITLE
No results in the browser

### ISSUE THREAD

**Issue by mitar** [meteortesting/meteor-mocha#64]
I am testing this package and I have one simple unit test, and I run in regular test mode (not full-app), but when I open the Meteor app in testing in the browser, I see results in the console, but no `div` is added anywhere in the DOM. (DOM is empty, besides script tags.)

Is there anything else one should do to see also results in the browser?

**Comment by serut** [comment]
If I'm right, you will see server tests in the console and frontend tests in the browser.

**Comment by aldeed** [comment]
As long as `TEST_BROWSER_DRIVER` env variable is not set, it should be adding the HTML. Maybe this broke at some point. Needs investigation.

**Comment by mitar** [comment]
I see. I was using `TEST_BROWSER_DRIVER`. I removed that and it works. Thanks.
