### ISSUE TITLE
Tests failing when looking for BrowserPolicy.content

### ISSUE THREAD

**Issue by etyp** [meteortesting/meteor-mocha#67]
We only use the `browser-policy-framing` package, which makes the check for `Package['browser-policy-common']` pass, but since we don't use `browser-policy-content` we get the following error on test runs now:

```
W20180608-17:13:06.473(0)? (STDERR) TypeError: Cannot read property 'allowInlineStyles' of undefined
W20180608-17:13:06.473(0)? (STDERR)     at server.js (packages/meteortesting:mocha/server.js:13:25)
```

It happens because the check [here assumes we're also using browser-policy-content](https://github.com/meteortesting/meteor-mocha/blob/a9eb0657f129b160dd405271ff6231571b3f8e4c/package/server.js#L8) though we're not. We didn't experience this before Meteor 1.7, which is odd.

It seems to me that this conditional should check for `browser-policy-common` AND `browser-policy-content`. Does that seem right?

**Comment by SimonSimCity** [comment]
@etyp does #68 solve this issue? If it does, please close this issue.
