### ISSUE TITLE
Garbled output on Meteor 1.7.0.3

### ISSUE THREAD

**Issue by thoni56** [meteortesting/meteor-mocha#72]
I get garbled output both in the console and in the browser for Meteor 1.7.0.3 which includes `meteortesting:mocha` 2.4.5_6.

To repeat:

    meteor create my-app
    cd my-app
    meteor add meteortesting:mocha
    meteor test --driver-package meteortesting:mocha

I created a [Stackoverflow question for this](https://stackoverflow.com/questions/51570393/garbled-test-result-output-from-meteortestingmocha), and also provided what worked for me, which was to replace `meteortesting:mocha` with `cultofcoders:mocha`.

**Comment by SimonSimCity** [comment]
Just ran it against the version currently on master here and it worked. I'll ping you when the release is ready.

**Comment by SimonSimCity** [comment]
I've published the latest version. Please update and reopen this issue if it still persists.

**Comment by thoni56** [comment]
Yes, it persists. It still, with 1.0.1, reports "Your app is crashing" and shows the garbled server logs although all tests are passing. I checked this on MacOS, will check on Linux and Windows when I get home.

    thomasmacbook:noteit thomas$ meteor list | grep meteortesting
    meteortesting:mocha        1.0.1  Run Meteor package or app tests with Mocha

**Comment by thoni56** [comment]
Uploaded with added .txt extension since GitHub doesn't support "that type of file" ;-)

[version.txt](https://github.com/meteortesting/meteor-mocha/files/2297041/version.txt)

**Comment by thoni56** [comment]
That comment led me to do `meteor update --all-packages` which did

    This project is already at Meteor 1.7.0.4, the latest release.
    
    Changes to your project's package version selections from updating package versions:
    
    lmieulet:meteor-coverage*    upgraded from 1.1.4 to 2.0.2
    meteorhacks:picker           removed from your project
    meteortesting:browser-tests  upgraded from 1.0.0 to 1.1.0
    meteortesting:mocha-core*    upgraded from 1.0.1 to 5.2.0_1

But still getting

    => Exited with code: 0
    => Your application is crashing. Waiting for file change.

**Comment by thoni56** [comment]
Just to be sure, I created a completely virgin project and the same thing happens there.

**Comment by SimonSimCity** [comment]
Sorry for the late response. I now got some time to take a new roundtrip on this and gave you a pretty long answer on stackoverflow 😌  https://stackoverflow.com/questions/51570393/garbled-test-result-output-from-meteortestingmocha/52365825#52365825

I have to admit that the first lines on the documentation need a rewrite and I welcome everyone to give me a good start.

Initially I focussed sorely about the changes which happened in the latest version and thought you were referring to a problem which just came up lately.

Please let me know what you're missing out on, and I hope you're still keen on using this testing framework in Meteor 😉

**Comment by SimonSimCity** [comment]
@thoni56 was what I wrote helpful to you? Is the issue still present? If I do not hear back from you by the end of this year, I'll close this issue due to missing feedback.

**Comment by amsully** [comment]
Stopping by to say this was helpful. I was running
```
TEST_BROWSER_DRIVER=chrome meteor test --full-app --driver-package meteortesting:mocha --port 3100
```
and received the `Your application is crashing. Waiting for file change.` issue.

Adding `TEST_WATCH=1` worked and resolved my issue for now.
versions:
```
meteortesting:mocha    1.1.1  Run Meteor package or app tests with Mocha
```
```
meteortesting:browser-tests@1.2.0
meteortesting:mocha-core@5.2.0_3
lmieulet:meteor-coverage@3.1.1
```

**Comment by thoni56** [comment]
Yes, your comments were helpful.

My concern isn't so much with meteortesting:meteor-mocha itself but rather the entry point for new users. As it is still (?) the recommended unittesting framework for Meteor I would really like it to be as simple to get started with as the instructions in the [Meteor Guide](https://guide.meteor.com/testing.html#mocha).

I suppose that is as much an issue with that instruction as with meteortesting:meteor-mocha, but I'd like it to be that simple to get working. I don't want to google or StackOverflow to find out how to get it to work.

I'm sure meteortesting:meteor-mocha could be made even simpler to get working with some reasonable defaults, so that it matches what you think it is when you read the guide.

**Comment by harmansingh2908** [comment]
I am trying to run test cases with meteor version 1.8 with this command

TEST_WATCH=1 meteor test --driver-package meteortesting:mocha --port 3100

It's throwing error : Error: ENOENT: no such file or directory, open '/private/var/folders/q4/rl0c5md979d6xz32795bxfrm0000gq/T/meteor-test-run1hflvik.7mvil/packages/implementation/settings.json'

I don't know what is the issue. I am not to much familiar with meteor.

**Comment by SimonSimCity** [comment]
@harmansingh2908 Not related to this issue. Please create a separate issue for it.

**Comment by SimonSimCity** [comment]
Updated the documentation of this package which should make it easier. I'll check the instructions at the Meteor Guide soon also.
