### ISSUE TITLE
*.test.* files not run

### ISSUE THREAD

**Issue by cmoses8626** [meteortesting/meteor-mocha#74]
Tests in the /tests directory are properly run and output to the console, but any *.test.* files outside of this directory are not picked up. Even when there's a syntax error in the *.test.* file, I get no error messages or failed tests.

Here's an example test file in the imports directory that is not run: https://github.com/cmoses8626/meteor-boilerplate/blob/master/imports/api/users.test.js

I'm on Meteor 1.7.1-beta.27. 

Still learning Meteor and how to do testing, so thanks for the help!

**Comment by aldeed** [comment]
@cmoses8626 This is most likely an issue with the Meteor 1.7.1 beta. Meteor is the one that gathers the test files. This package merely runs them. Please try with latest stable Meteor and, if that works, submit an issue in the meteor/meteor repo.
