### ISSUE TITLE
Exit Code !== 0

### ISSUE THREAD

**Issue by thebarty** [meteortesting/meteor-mocha#79]
Hi guys,

the testrunner runs, BUT after it is done the command exits with an error-exit-code (!==0) and stops my Gitlab skript.

Any idea what might cause the command to exit with an error code?
```
SERVER_TEST_REPORTER=xunit XUNIT_FILE=$PWD/unit-integrationa-results.xml meteor test --once --driver-package meteortesting:mocha --allow-superuser
```

```
ERROR: Job failed: exit code 1
```

**Comment by thebarty** [comment]
@SimonSimCity yes, you were right. It exists with a non-zero, if a test fails.

I wanted to continue with my acceptance tests and this is my solution:
`SERVER_TEST_REPORTER=xunit XUNIT_FILE=$PWD/test-results-unit-integrational.xml meteor test --once --driver-package meteortesting:mocha --settings settings-unittests-ci.json --allow-superuser || true  # prevent failing mocha-tests to result in exit 1 (which would exit Gitlab). Always continue with acceptance-tests`

**Comment by SimonSimCity** [comment]
Just for interest ... why do you want this hack? You want a CI to fail if the tests fail, right?

Hint: If you want a couple of commands to run through and to let it fail if either one failed, this could help:

```bash
meteor test || CRASHED=1
meteor test --full-app || CRASHED=1
if [ "$CRASHED" ]; then exit 1; fi
