### ISSUE TITLE
Bump meteor-browser-tests to 1.1.0

### ISSUE THREAD

**Issue by FishSaidNo** [meteortesting/meteor-mocha#83]
Would this be possible?
I'm unsure how the versioning / release process works for this package.

Cheers!

**Comment by SimonSimCity** [comment]
The latest changes of this package are just shipped as `1.0.1` - so what should be the reason to ship a new release?

**Comment by FishSaidNo** [comment]
I was referring to this packages `meteortesting:browser-tests` dependency (which is @1.0.0 in package.js)

I've realised that being a minor version change this can be updated/overridden from within the project itself. After removing a mistakenly placed `@=` version lock in my package file.

My apologies for the non-issue.
