### ISSUE TITLE
Issues with xml output for CI

### ISSUE THREAD

**Issue by MKRazz** [meteortesting/meteor-mocha#87]
I'm trying to use the `xunit` reporter to get output files for CI. The server is working fine, but I'm having trouble with the client. The output isn't containing any of the opening xml, and the closing tags are partially rendering but with unicode escape strings (`\u003C`).

After some debugging I was able to get it to work, I was considering creating a PR but I'm not sure which project it belongs, or if maybe there's a simpler way to resolve this that I'm not seeing.

I'm using `selenium-webdriver@3.6.0` with `chromedriver@2.46.0` for the client driver.

The first issue is that the stdout coming from `meteortesting:browser-tests@1.0.0` has completely stripped the initial xml, but if I update the dependency to `meteortesting:browser-tests@1.2.0` I now receive that data. I didn't look at what changed between the versions, but it did fix that part of the issue.

The second issue is that the data has unicode escaped strings instead of the actual characters. After some quick searching, my preferred solution was to use this: 
```decodeURIComponent(JSON.parse(`"${data.toString()}"`))```
Double quote is also being escaped, so wrapping the full string in double quotes for `JSON.parse` seems fine, and this will unescape the unicode characters and the quotes, giving me the desired output.

Is there a simpler way to resolve this? Like am I missing an encoding option or something? Or maybe a different client driver or version?

Thanks,

-Matt

**Comment by SimonSimCity** [comment]
Could very well be that my fix on [`meteortesting:browser-tests@1.2.0`](https://github.com/meteortesting/meteor-browser-tests/blob/master/CHANGELOG.md#120) (which actually was an attempt to fix something else) also fixe this 😌

Meteor should actually (when calling `meteor update`) also update the package `meteortesting:browser-tests` which this package depends on - but sometimes I have to do some steps manually to get it work.

To the encoding: This seems all to be quite aligned with the standard - at least an online-parser like https://jsonformatter.org/xml-parser shows me the correct values.

**Comment by MKRazz** [comment]
> Meteor should actually (when calling `meteor update`) also update the package `meteortesting:browser-tests` which this package depends on - but sometimes I have to do some steps manually to get it work.

This package specifically uses `1.0.0` in package.js so I don't think that'll update with the command.

**Comment by SimonSimCity** [comment]
Well, according to https://docs.meteor.com/api/packagejs.html#PackageAPI-use this means "this or a higher compatible version", whereby `1.2.0` is considered compatible to `1.0.0`. If it wouldn't be compatible you'd have to force the version which would maybe downgrade other packages to fulfill the requirement.

**Comment by MKRazz** [comment]
Cool, didn't know that, I'll see if I can get it to update.

**Comment by SimonSimCity** [comment]
Added again another update - `1.3.0` - which should have a better fix for a.o. also this issue.
