### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by mexin** [meteortesting/meteor-mocha#89]
Im trying to exclude some files but cannot find a way to completely avoid them, is there any special configuration that needs to be added?

Thanks in advance!

**Comment by SimonSimCity** [comment]
In this package can only control which tests are executed, regulated by the following options:

https://github.com/meteortesting/meteor-mocha/tree/e5e0f3c91c78ec0a079a6d948291be40b0bbb5ff#run-tests-inclusively-grep-or-exclusively-invert

If you want to control which files are loaded, please check https://guide.meteor.com/testing.html#test-modes and additionally scan the changelog (https://docs.meteor.com/changelog.html) for the term `testModule`. The latter option should be better linked throughout the rest of the meteor guide, if you ask me.
