### ISSUE TITLE
client/compatibility js files

### ISSUE THREAD

**Issue by mohamedatef98-lincx** [meteortesting/meteor-mocha#97]
We have some js files inside our `client/compatibility` directory, And they are loaded properly in production and development environments.
But when running `meteor test` without the `—full-app` these files aren’t loaded.

**Comment by SimonSimCity** [comment]
To me this rather sounds like a misconfiguration than a bug. Since you're here talking about the client-side of the tests, I almost expect you only run the server-side tests. How do you run the tests?

**Comment by SimonSimCity** [comment]
Please keep in mind that `*.test[s].*`, or `*.spec[s].*` files are only auto-included when running your app in test-mode without the `--full-app` flag. If you add this flag only files matching `*.app-test[s].*` or `*.app-spec[s].*` are included. - And you have to add two dashes for the parameter.

More details: https://guide.meteor.com/testing.html#test-modes

**Comment by SimonSimCity** [comment]
Closing this issue since this package has no responsibility for which files are loaded and which not - this all is regulated by Meteor.
